-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
}
local Event = game:GetService("Workspace")["__THINGS"]["__REMOTES"]["get invites open"]
Event:InvokeServer(A_1)

-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "08a9b45a-bc19-475f-af97-9637371fd7fc", 
	[2] = 2516224372
}
local Event = game:GetService("Workspace")["__THINGS"]["__REMOTES"]["invite to bank"]
Event:InvokeServer(A_1)


